// https://creativecommons.org/licenses/by-sa/3.0/deed.de


= Vorwort =

RELAX NG ist eine Schemasprache für XML, mit der man den Aufbau eines XML-Dokuments beschreiben kann.
Hat man ein solches Schema erstellt, dann kann man leicht überprüfen, ob ein XML-Dokument den Anforderungen entspricht.
Beispielsweise kann man in einem Schema festlegen, dass ein Adressbucheintrag genau einen Vornamen und einen Nachnamen enthalten muss.
Das hat zwei Vorteile:

. Der Anwender kann prüfen, ob das XML-Dokument den Anforderungen entspricht (Validierung).
. Mit einem passenden Editor kann sich per Autovervollständigung Vorschläge für die Eingabe geben lassen und spart Tipparbeit und vermeidet Fehler.

Die Schemasprache RELAX NG eignet sich sehr gut für diese Aufgabe und wird von vielen XML-Editoren unterstützt.
RELAX NG kommt in zwei Arten daher, die funktional identisch sind.
Einmal als »kompakte Syntax« und einmal als »XML-Syntax«. In diesem Dokument wird nur die XML-Syntax beschrieben.

Dieses Tutorial lehnt sich an das »offizielle« Tutorial an, das auf der http://relaxng.org/tutorial-20030326.html[RELAX NG-Webseite zur Verfügung steht].
Es ist keine direkte Übersetzung.
Hier und da wurden Änderungen vorgenommen, um den Inhalt leichter zu vermitteln.
Hinweise auf nicht mehr übliche Techniken wurden entfernt (TREX, DTD, ...)


ifndef::ebook-format[]
TIP: Neu eingeführte Elemente werden im linken Rand dargestellt. Damit kannst du das Tutorial auch »überfliegen«, wenn du nach einem bestimmten Befehl suchst. Das funktioniert leider nur, wenn der Bildschirm groß genug ist...
endif::[]

Dieses Dokument unterliegt der https://creativecommons.org/licenses/by-sa/3.0/deed.de[CC-By-SA Lizenz]. Der Quelltext (Asciidoctor) des Dokuments ist auf https://github.com/speedata/relaxngtutorial-de[Github] zu finden.
ifdef::ebook-format[]
Den Autor kann man unter gundlach@speedata.de kontaktieren.
endif::[]


// Ende der Datei


